# Global configurations
global:
  namespace: blog-app
  imagePullPolicy: IfNotPresent

# Backend service details
backend:
  replicaCount: 2
  image:
    repository: alisial45/blog-app-backend
    tag: "16479734724"
  service:
    port: 8080
    targetPort: 8080
  config:
    frontend_url: http://3.109.183.209:32747/

# Frontend service details
frontend:
  replicaCount: 2
  image:
    repository: alisial45/blog-app-frontend
    tag: "16479734724"
  service:
    port: 5173
    targetPort: 5173
    config:
    vite_api_url: http://3.109.183.209:32747/backend

