# Global configurations
global:
  namespace: mern-blog-app
  imagePullPolicy: IfNotPresent

# Backend service details
backend:
  replicaCount: 2
  image:
    repository: alisial45/blog-app-backend
    tag: latest
  service:
    type: NodePort
    port: 8080
    targetPort: 8080
    nodePort : 31100
  config:
    frontend_url: "http://65.0.31.133:5173"

# Frontend service details
frontend:
  replicaCount: 2
  image:
    repository: alisial45/blog-app-frontend
    tag: latest
  service:
    type: NodePort
    port: 5173
    targetPort: 5173
    nodePort : 31000
  config:
    vite_api_url: "http://65.0.31.133:5173"
